name: build_and_test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  windows:
    runs-on: windows-2019
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      shell: powershell
      run: cmake -S . -B ${{runner.workspace}}/build
    - name: Build
      shell: powershell
      run: cmake --build ${{runner.workspace}}/build  --config $BUILD_TYPE -j2
    - name: Test
      shell: powershell
      run: build\ClangBuildAnalyzer.exe --test tests
    - uses: actions/upload-artifact@v1
      with:
        name: ClangBuildAnalyzer-win.exe
        path: build/ClangBuildAnalyzer.exe


  mac:
    runs-on: macOS-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake Debug
      run: cmake -S . -B ${{runner.workspace}}/build/Debug -DCMAKE_BUID_TYPE=Debug
    - name: Build Debug
      run: cmake --build ${{runner.workspace}}/build/Debug -j2
    - name: Configure CMake Release
      run: cmake -S . -B ${{runner.workspace}}/build/Release -DCMAKE_BUID_TYPE=Release
    - name: Build Release
      run: cmake --build ${{runner.workspace}}/build/Release -j2
    - name: Test
      run: build/Release/ClangBuildAnalyzer --test tests
    - uses: actions/upload-artifact@v1
      with:
        name: ClangBuildAnalyzer-mac
        path: projects/xcode/build/Release/ClangBuildAnalyzer

  linux:
    runs-on: ubuntu-16.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Ubuntu16 Gcc7
      env:
        CC: gcc-7
        CXX: g++-7
      run: |
        mkdir buildCmake
        cd buildCmake
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j 2
        cd ..
        buildCmake/ClangBuildAnalyzer --test tests
        make -f projects/make/Makefile -j 2
        build/ClangBuildAnalyzer --test tests
    - uses: actions/upload-artifact@v1
      with:
        name: ClangBuildAnalyzer-linux
        path: build/ClangBuildAnalyzer

